(()=>{
  const loader=document.createElement('script');
  loader.src='app-v6.js?v=6';
  loader.onload=waitForBase;
  loader.onerror=()=>alert('TriLedger could not load its finance engine. Refresh while online.');
  document.body.appendChild(loader);

  function waitForBase(){
    let tries=0;
    const timer=setInterval(()=>{
      tries++;
      try{
        if(typeof S!=='undefined' && typeof cats!=='undefined' && typeof render==='function' && typeof window.openIncome==='function'){
          clearInterval(timer);setupV7();
        }else if(tries>200){clearInterval(timer);console.error('TriLedger v7 timed out waiting for v6')}
      }catch(e){if(tries>200){clearInterval(timer);console.error(e)}}
    },50);
  }

  function setupV7(){
    if(window.__triledgerV7)return;window.__triledgerV7=true;
    migrateV7();addV7Styles();addPlanningUI();patchCoreFunctions();processRecurring();processShortcutImport();
    render();renderV7();
  }

  function migrateV7(){
    if(!Array.isArray(S.recurring))S.recurring=[];
    if(!Array.isArray(S.goals))S.goals=[];
    if(!S.reconciliations||typeof S.reconciliations!=='object')S.reconciliations={};
    if(!S.merchantRules||typeof S.merchantRules!=='object')S.merchantRules={};
    if(!Array.isArray(S.importFingerprints))S.importFingerprints=[];
    S.schemaVersion=7;persist();
  }

  function addV7Styles(){
    if(document.getElementById('v7styles'))return;
    const st=document.createElement('style');st.id='v7styles';st.textContent=`
      .v7-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.v7-stat{border:1px solid var(--l);background:#0b1525;border-radius:13px;padding:12px}.v7-stat strong{display:block;font-size:19px;margin-top:4px}.v7-list{display:flex;flex-direction:column;gap:8px}.v7-alert{border:1px solid #725d2d;background:#251f12;border-radius:13px;padding:11px}.v7-alert.over{border-color:#714047;background:#261518}.v7-good{border:1px solid #285a45;background:#10241c;border-radius:13px;padding:11px}.v7-line{display:flex;justify-content:space-between;gap:12px;align-items:center}.v7-line>*{min-width:0}.v7-progress{height:9px;background:#17243a;border-radius:999px;overflow:hidden;margin-top:7px}.v7-progress i{display:block;height:100%;background:var(--a)}.v7-chip{display:inline-flex;padding:3px 7px;border:1px solid var(--l);border-radius:999px;font-size:11px;color:var(--m)}.v7-positive{color:#9ce8c3}.v7-negative{color:#ffc1c6}.v7-textarea{width:100%;min-height:92px;resize:vertical}.split-row{display:grid;grid-template-columns:1fr 130px auto;gap:7px;align-items:end}.v7-section{margin-top:18px}.v7-note{font-size:12px;color:var(--m);margin-top:6px}.v7-inline{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.v7-inline input,.v7-inline select{min-width:0}.v7-report{white-space:pre-wrap;line-height:1.5}.v7-table{display:grid;gap:6px}.v7-table-row{display:grid;grid-template-columns:1fr auto auto;gap:10px;padding:8px 0;border-bottom:1px solid var(--l)}
      @media(max-width:650px){.v7-grid{grid-template-columns:1fr}.split-row{grid-template-columns:1fr 105px auto}.v7-table-row{grid-template-columns:1fr auto}.v7-table-row .hide-mobile{display:none}}
    `;document.head.appendChild(st);
  }

  function addPlanningUI(){
    if(document.getElementById('planning'))return;
    const nav=document.querySelector('.tabs');
    const b=document.createElement('button');b.dataset.v='planning';b.textContent='Plan & Reports';nav.appendChild(b);
    const sec=document.createElement('section');sec.id='planning';sec.className='view';sec.innerHTML=`
      <div class="toolbar"><div><h2>Plan & Reports</h2><small>Budgets, recurring items, goals, bank imports and reconciliation.</small></div><button class="primary" type="button" onclick="renderV7()">Refresh</button></div>
      <div id="budgetAlertsPanel"></div>
      <div class="v7-section"><h2>Budget status & daily allowance</h2><div id="budgetInsights" class="v7-list"></div></div>
      <div class="v7-section"><h2>Month comparison</h2><div id="monthComparison" class="panel"></div></div>
      <div class="v7-section"><div class="toolbar"><h2>Recurring transactions</h2><button class="primary" type="button" onclick="openRecurring()">+ Recurring</button></div><div id="recurringList" class="v7-list"></div></div>
      <div class="v7-section"><div class="toolbar"><h2>Savings goals</h2><button class="primary" type="button" onclick="openGoal()">+ Goal</button></div><div id="goalList" class="v7-list"></div></div>
      <div class="v7-section"><h2>Bank reconciliation</h2><div class="panel forms"><label>Account<select id="reconAccount"></select></label><label>Actual bank balance<input id="reconActual" type="number" step="0.01" inputmode="decimal"></label><label class="full">Note<input id="reconNote" placeholder="e.g. balance shown in TPBank app"></label><button class="primary full" type="button" onclick="saveReconciliation()">Reconcile</button></div><div id="reconList" class="v7-list" style="margin-top:10px"></div></div>
      <div class="v7-section"><h2>Bank import</h2><div class="panel"><div class="actions"><label><input id="bankCsvInput" type="file" accept=".csv,text/csv" hidden onchange="importBankCsv(this)"><button type="button" onclick="bankCsvInput.click()">Import bank CSV</button></label></div><div class="v7-note">CSV import detects common date, description, debit/credit, amount, currency and account columns and skips duplicates.</div><hr style="border:0;border-top:1px solid var(--l);margin:14px 0"><label>Paste a bank alert / SMS<textarea id="bankAlertText" class="v7-textarea" placeholder="Paste TPBank, Techcombank, BIDV or Serbian bank transaction alert here"></textarea></label><div class="v7-inline" style="margin-top:8px"><select id="bankAlertAccount"></select><button class="primary" type="button" onclick="importBankAlert()">Import alert</button></div><div class="v7-note">For iPhone Shortcuts automation, TriLedger also accepts URL parameters such as ?bank=tpbank&type=expense&amount=278000&currency=VND&rsd=590&merchant=MAXI.</div><div id="bankImportStatus" class="v7-note"></div></div></div>
      <div class="v7-section"><div class="toolbar"><div><h2>Monthly report</h2><small>Income, spending, savings, categories and unusual expenses.</small></div><div class="v7-inline"><input id="reportMonth" type="month"><button type="button" onclick="renderMonthlyReport()">View</button><button type="button" onclick="exportMonthlyCsv()">Export CSV</button></div></div><div id="monthlyReport" class="panel v7-report"></div></div>
      <div class="v7-section"><h2>Merchant memory</h2><div id="merchantRulesList" class="v7-list"></div></div>
    `;
    document.querySelector('main').appendChild(sec);
    b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id==='planning'));renderV7()};
    createDialogs();
    const rm=document.getElementById('reportMonth');if(rm)rm.value=month();
  }

  function createDialogs(){
    if(document.getElementById('recurringDlg'))return;
    document.body.insertAdjacentHTML('beforeend',`
      <dialog id="recurringDlg"><form class="forms" onsubmit="saveRecurring(event)"><input id="recurringId" type="hidden"><label>Type<select id="recurringType"><option>Expense</option><option>Income</option></select></label><label>Day of month<input id="recurringDay" type="number" min="1" max="31" value="1" required></label><label class="full">Account<select id="recurringAccount"></select></label><label>Amount<input id="recurringAmount" type="number" min="0.01" step="0.01" required></label><label>Amount currency<select id="recurringCurrency"><option>RSD</option><option>VND</option><option>EUR</option></select></label><label>Category<select id="recurringCategory"></select></label><label class="full">Description<input id="recurringDesc" required placeholder="Rent, salary, Netflix..."></label><div class="actions full"><button type="button" onclick="recurringDlg.close()">Cancel</button><button class="primary">Save recurring</button></div></form></dialog>
      <dialog id="goalDlg"><form class="forms" onsubmit="saveGoal(event)"><input id="goalId" type="hidden"><label class="full">Goal name<input id="goalName" required placeholder="Emergency fund, apartment deposit..."></label><label>Target amount<input id="goalTarget" type="number" min="0.01" step="0.01" required></label><label>Currency<select id="goalCurrency"><option>RSD</option><option>EUR</option><option>VND</option></select></label><label>Saved already<input id="goalSaved" type="number" min="0" step="0.01" value="0"></label><label>Target date<input id="goalDate" type="date"></label><div class="actions full"><button type="button" onclick="goalDlg.close()">Cancel</button><button class="primary">Save goal</button></div></form></dialog>
      <dialog id="contributeDlg"><form class="forms" onsubmit="saveContribution(event)"><input id="contributeGoalId" type="hidden"><label class="full">Add to goal<input id="contributeAmount" type="number" min="0.01" step="0.01" required></label><div class="actions full"><button type="button" onclick="contributeDlg.close()">Cancel</button><button class="primary">Add</button></div></form></dialog>
      <dialog id="splitDlg"><form class="forms" onsubmit="saveSplit(event)"><input id="splitTxId" type="hidden"><div class="full"><strong id="splitTotalLabel"></strong><div class="v7-note">Allocate the full RSD total across categories.</div></div><div id="splitRows" class="full v7-list"></div><button class="full" type="button" onclick="addSplitRow()">+ Split line</button><div class="actions full"><button type="button" onclick="splitDlg.close()">Cancel</button><button class="primary">Save split</button></div></form></dialog>
    `);
  }

  function patchCoreFunctions(){
    const originalSave=save;save=function(){originalSave();renderV7()};
    const oldSaveTx=saveTx;saveTx=function(e){const merchant=(tdesc.value||'').trim(),category=tcat.value;oldSaveTx(e);if(merchant&&category&&category!=='Split')rememberMerchant(merchant,category);persist();renderV7()};
    const oldReceiptCategory=receiptCategory;receiptCategory=function(text){const x=normalize(text);for(const [m,c] of Object.entries(S.merchantRules||{}).sort((a,b)=>b[0].length-a[0].length))if(m.length>=3&&x.includes(m))return c;return oldReceiptCategory(text)};
    txRows=function(list,edit=false){return list.length?list.map(t=>{let a=acc(t.account),cl=(t.type||'').toLowerCase(),sg=t.type==='Expense'?'−':t.type==='Income'?'+':'↔',main=t.type==='Expense'?money(txRsd(t),'RSD'):(a?money(t.amount,a.currency):money(t.amount,'VND')),pair=t.type==='Expense'&&a?.currency==='VND'?`${money(txVnd(t),'VND')} bank debit`:'';return `<div class="row"><div><strong>${esc(t.desc||t.type)}</strong><small>${esc(t.date||'')} · ${esc(a?.name||'')}${t.category?' · '+esc(t.category):''}${t.splits?.length?' · '+t.splits.length+' splits':''}${t.receiptScanned?' · 📷 Receipt':''}${t.imported?' · Bank import':''}${t.recurringId?' · Recurring':''}</small></div><div class="row-right"><span class="amount ${cl}">${sg}${main}</span>${pair?`<div class="secondary">${pair}</div>`:''}${edit?`<div class="actions" style="justify-content:flex-end;margin-top:5px">${t.type==='Expense'?`<button onclick="openSplit('${t.id}')">Split</button>`:''}<button onclick="editTx('${t.id}')">Edit</button><button onclick="delTx('${t.id}')">Delete</button></div>`:''}</div></div>`}).join(''):'<div class="empty">No transactions yet</div>'};
    categoryRows=function(expenses){const sums={};for(const t of expenses)for(const p of expenseParts(t))sums[p.category]=(sums[p.category]||0)+p.rsdAmount;const arr=Object.entries(sums).sort((a,b)=>b[1]-a[1]),total=arr.reduce((x,[,v])=>x+v,0);if(!arr.length)return '<div class="empty">No expenses this month yet</div>';return arr.map(([c,v])=>`<div class="catrow"><strong>${esc(c)}</strong><div class="catbar"><i style="width:${total?Math.max(2,v/total*100):0}%"></i></div><div class="row-right"><strong>${money(v,'RSD')}</strong><small>${total?Math.round(v/total*100):0}%</small></div></div>`).join('')+`<div class="help" style="margin-top:10px">Total categorized: ${money(total,'RSD')}</div>`};
    budgetRows=function(){const m=month(),days=daysLeftInMonth();return S.budgets.length?S.budgets.map(b=>{const spent=budgetSpent(b,m),remaining=b.amount-spent,pct=b.amount?spent/b.amount*100:0,daily=Math.max(0,remaining)/days;return `<div class="row"><div><strong>${esc(b.category)} <span class="v7-chip">${pct>=100?'OVER':pct>=80?'80%+':'OK'}</span></strong><small>${esc(b.scope)} · ${money(spent,b.currency)} of ${money(b.amount,b.currency)}</small><div class="budgetbar"><i style="width:${Math.min(100,pct)}%"></i></div><div class="help">${remaining>=0?money(remaining,b.currency)+' remaining · '+money(daily,b.currency)+'/day':'Over by '+money(Math.abs(remaining),b.currency)}</div></div><button onclick="delBudget('${b.id}')">Delete</button></div>`}).join(''):'<div class="empty">No budgets yet</div>'};
  }

  function normalize(s){return String(s||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9čćšđž]+/g,' ').replace(/\s+/g,' ').trim()}
  function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function rememberMerchant(merchant,category){const key=normalize(merchant).slice(0,60);if(key.length>=3)S.merchantRules[key]=category}
  function expenseParts(t){return Array.isArray(t.splits)&&t.splits.length?t.splits.map(s=>({category:s.category||'Other',rsdAmount:+s.rsdAmount||0})):[{category:t.category||'Other',rsdAmount:txRsd(t)}]}
  function daysLeftInMonth(){const d=new Date(),last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate();return Math.max(1,last-d.getDate()+1)}
  function monthKeyOffset(o){const d=new Date();d.setMonth(d.getMonth()+o);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
  function monthExpenses(m){return S.tx.filter(t=>t.type==='Expense'&&t.date?.startsWith(m))}
  function monthIncome(m){return S.tx.filter(t=>t.type==='Income'&&t.date?.startsWith(m))}
  function sumExpenseRsd(a){return a.reduce((x,t)=>x+txRsd(t),0)}function sumIncomeRsd(a){return a.reduce((x,t)=>x+txRsd(t),0)}
  function budgetSpent(b,m){const rel=S.tx.filter(t=>t.type==='Expense'&&t.date?.startsWith(m)&&acc(t.account)?.scope===b.scope);let rsd=0;for(const t of rel)for(const p of expenseParts(t))if(p.category===b.category)rsd+=p.rsdAmount;return b.currency==='RSD'?rsd:b.currency==='VND'?conv(rsd,'RSD','VND'):conv(rsd,'RSD','EUR')}
  function categoryMap(list){const o={};for(const t of list)for(const p of expenseParts(t))o[p.category]=(o[p.category]||0)+p.rsdAmount;return o}

  window.renderV7=function(){if(!document.getElementById('planning'))return;fillV7AccountSelects();renderBudgetInsights();renderMonthComparison();renderRecurring();renderGoals();renderReconciliation();renderMonthlyReport();renderMerchantRules()};
  function fillV7AccountSelects(){const opts=S.accounts.filter(a=>!a.planned).map(a=>`<option value="${a.id}">${esc(a.name)} · ${a.currency}</option>`).join('');['reconAccount','bankAlertAccount','recurringAccount'].forEach(id=>{const el=document.getElementById(id);if(el){const v=el.value;el.innerHTML=opts;if(v&&[...el.options].some(o=>o.value===v))el.value=v}});const rc=document.getElementById('recurringCategory');if(rc){const v=rc.value;rc.innerHTML=cats.map(c=>`<option>${esc(c)}</option>`).join('');if(v)rc.value=v}}
  function renderBudgetInsights(){const el=document.getElementById('budgetInsights'),alerts=document.getElementById('budgetAlertsPanel');if(!el||!alerts)return;const m=month(),days=daysLeftInMonth();let ah=[];if(!S.budgets.length){el.innerHTML='<div class="empty">Add monthly budgets to see remaining money and daily allowances.</div>';alerts.innerHTML='';return}el.innerHTML=S.budgets.map(b=>{const spent=budgetSpent(b,m),rem=b.amount-spent,pct=b.amount?spent/b.amount*100:0,daily=Math.max(0,rem)/days;if(pct>=100)ah.push(`<div class="v7-alert over"><strong>${esc(b.category)} is over budget</strong>${money(spent-b.amount,b.currency)} over the monthly limit.</div>`);else if(pct>=80)ah.push(`<div class="v7-alert"><strong>${esc(b.category)} is at ${Math.round(pct)}%</strong>${money(rem,b.currency)} left for this month.</div>`);return `<div class="v7-stat"><div class="v7-line"><strong>${esc(b.category)}</strong><span>${Math.round(pct)}%</span></div><div class="v7-progress"><i style="width:${Math.min(100,pct)}%"></i></div><div class="v7-grid" style="margin-top:8px"><div><small>Remaining</small><strong>${money(rem,b.currency)}</strong></div><div><small>Safe daily spend</small><strong>${money(daily,b.currency)}</strong></div></div></div>`}).join('');alerts.innerHTML=ah.length?`<h2>Budget warnings</h2><div class="v7-list">${ah.join('')}</div>`:''}
  function renderMonthComparison(){const el=document.getElementById('monthComparison');if(!el)return;const cur=monthKeyOffset(0),prev=monthKeyOffset(-1),ce=monthExpenses(cur),pe=monthExpenses(prev),c=sumExpenseRsd(ce),p=sumExpenseRsd(pe),diff=c-p,pct=p?diff/p*100:null,cs=categoryMap(ce),ps=categoryMap(pe),changes=[...new Set([...Object.keys(cs),...Object.keys(ps)])].map(k=>[k,(cs[k]||0)-(ps[k]||0)]).sort((a,b)=>Math.abs(b[1])-Math.abs(a[1])).slice(0,5);el.innerHTML=`<div class="v7-grid"><div class="v7-stat"><small>${cur} spending</small><strong>${money(c,'RSD')}</strong></div><div class="v7-stat"><small>vs ${prev}</small><strong class="${diff>0?'v7-negative':'v7-positive'}">${diff>=0?'+':''}${money(diff,'RSD')}${pct===null?'':` (${pct>=0?'+':''}${pct.toFixed(1)}%)`}</strong></div></div><div class="v7-table" style="margin-top:10px">${changes.map(([k,v])=>`<div class="v7-table-row"><span>${esc(k)}</span><strong class="${v>0?'v7-negative':'v7-positive'}">${v>=0?'+':''}${money(v,'RSD')}</strong><span class="hide-mobile">${money(cs[k]||0,'RSD')}</span></div>`).join('')||'<div class="empty">No comparison data yet.</div>'}</div>`}

  window.openRecurring=function(id=''){fillV7AccountSelects();const r=S.recurring.find(x=>x.id===id);recurringId.value=r?.id||'';recurringType.value=r?.type||'Expense';recurringDay.value=r?.day||1;recurringAccount.value=r?.account||'tpbank';recurringAmount.value=r?.amount||'';recurringCurrency.value=r?.currency||'RSD';recurringCategory.value=r?.category||'Other';recurringDesc.value=r?.desc||'';recurringDlg.showModal()};
  window.saveRecurring=function(e){e.preventDefault();const obj={id:recurringId.value||crypto.randomUUID(),type:recurringType.value,day:Math.min(31,Math.max(1,+recurringDay.value||1)),account:recurringAccount.value,amount:+recurringAmount.value||0,currency:recurringCurrency.value,category:recurringCategory.value,desc:recurringDesc.value.trim(),active:true,lastGenerated:''};if(obj.amount<=0)return alert('Enter an amount.');const i=S.recurring.findIndex(x=>x.id===obj.id);if(i>=0){obj.lastGenerated=S.recurring[i].lastGenerated||'';S.recurring[i]=obj}else S.recurring.push(obj);recurringDlg.close();save()};
  window.toggleRecurring=id=>{const r=S.recurring.find(x=>x.id===id);if(r){r.active=!r.active;save()}};window.deleteRecurring=id=>{if(confirm('Delete recurring item?')){S.recurring=S.recurring.filter(x=>x.id!==id);save()}};
  function renderRecurring(){const el=document.getElementById('recurringList');if(!el)return;el.innerHTML=S.recurring.length?S.recurring.map(r=>`<div class="row"><div><strong>${esc(r.desc)}</strong><small>${r.type} · day ${r.day} · ${esc(acc(r.account)?.name||'')} · ${esc(r.category)} ${r.active?'':'· PAUSED'}</small></div><div class="row-right"><strong>${money(r.amount,r.currency)}</strong><div class="actions" style="justify-content:flex-end"><button onclick="openRecurring('${r.id}')">Edit</button><button onclick="toggleRecurring('${r.id}')">${r.active?'Pause':'Resume'}</button><button onclick="deleteRecurring('${r.id}')">Delete</button></div></div></div>`).join(''):'<div class="empty">No recurring transactions yet.</div>'}
  function processRecurring(){const now=new Date(),m=month(),today=now.getDate(),last=new Date(now.getFullYear(),now.getMonth()+1,0).getDate();let added=0;for(const r of S.recurring){if(!r.active||r.lastGenerated===m||Math.min(r.day,last)>today)continue;const a=acc(r.account);if(!a||a.planned)continue;const d=`${m}-${String(Math.min(r.day,last)).padStart(2,'0')}`;let amount,rsdAmount,vndAmount;if(r.type==='Expense'){rsdAmount=r.currency==='RSD'?r.amount:conv(r.amount,r.currency,'RSD');vndAmount=conv(rsdAmount,'RSD','VND');amount=a.currency==='RSD'?rsdAmount:a.currency==='VND'?vndAmount:conv(rsdAmount,'RSD','EUR')}else{amount=conv(r.amount,r.currency,a.currency);rsdAmount=conv(amount,a.currency,'RSD');vndAmount=conv(amount,a.currency,'VND')}S.tx.push({id:crypto.randomUUID(),type:r.type,date:d,account:r.account,to:'',amount,rsdAmount,vndAmount,category:r.category,desc:r.desc,recurringId:r.id,rsdConfirmed:r.type!=='Expense'});r.lastGenerated=m;added++}if(added)persist()}

  window.openGoal=function(id=''){const g=S.goals.find(x=>x.id===id);goalId.value=g?.id||'';goalName.value=g?.name||'';goalTarget.value=g?.target||'';goalCurrency.value=g?.currency||'RSD';goalSaved.value=g?.saved||0;goalDate.value=g?.date||'';goalDlg.showModal()};
  window.saveGoal=function(e){e.preventDefault();const g={id:goalId.value||crypto.randomUUID(),name:goalName.value.trim(),target:+goalTarget.value||0,currency:goalCurrency.value,saved:+goalSaved.value||0,date:goalDate.value};if(g.target<=0)return alert('Enter a target amount.');const i=S.goals.findIndex(x=>x.id===g.id);if(i>=0)S.goals[i]=g;else S.goals.push(g);goalDlg.close();save()};
  window.openContribution=id=>{const g=S.goals.find(x=>x.id===id);if(!g)return;contributeGoalId.value=id;contributeAmount.value='';contributeDlg.showModal()};window.saveContribution=function(e){e.preventDefault();const g=S.goals.find(x=>x.id===contributeGoalId.value),n=+contributeAmount.value||0;if(!g||n<=0)return;g.saved+=n;contributeDlg.close();save()};window.deleteGoal=id=>{if(confirm('Delete savings goal?')){S.goals=S.goals.filter(x=>x.id!==id);save()}};
  function renderGoals(){const el=document.getElementById('goalList');if(!el)return;el.innerHTML=S.goals.length?S.goals.map(g=>{const pct=g.target?Math.min(100,g.saved/g.target*100):0,rem=Math.max(0,g.target-g.saved);return `<div class="v7-stat"><div class="v7-line"><div><strong>${esc(g.name)}</strong><small>${g.date?'Target '+esc(g.date):'No target date'}</small></div><strong>${Math.round(pct)}%</strong></div><div class="v7-progress"><i style="width:${pct}%"></i></div><div class="v7-line" style="margin-top:8px"><span>${money(g.saved,g.currency)} saved · ${money(rem,g.currency)} left</span><div class="actions"><button onclick="openContribution('${g.id}')">+ Save</button><button onclick="openGoal('${g.id}')">Edit</button><button onclick="deleteGoal('${g.id}')">Delete</button></div></div></div>`}).join(''):'<div class="empty">No savings goals yet.</div>'}

  window.saveReconciliation=function(){const id=reconAccount.value,a=acc(id),actual=+reconActual.value;if(!a||!Number.isFinite(actual))return alert('Enter the actual bank balance.');S.reconciliations[id]={actual,date:new Date().toISOString(),note:reconNote.value.trim()};reconActual.value='';reconNote.value='';save()};
  function renderReconciliation(){const el=document.getElementById('reconList');if(!el)return;const items=Object.entries(S.reconciliations).filter(([id])=>acc(id));el.innerHTML=items.length?items.map(([id,r])=>{const a=acc(id),calc=bal(id),diff=r.actual-calc;return `<div class="row"><div><strong>${esc(a.name)}</strong><small>${new Date(r.date).toLocaleString()}${r.note?' · '+esc(r.note):''}</small></div><div class="row-right"><strong>${money(r.actual,a.currency)} actual</strong><div class="secondary ${Math.abs(diff)>0.01?'v7-negative':'v7-positive'}">Difference ${money(diff,a.currency)}</div></div></div>`}).join(''):'<div class="empty">No reconciliations yet.</div>'}

  window.openSplit=function(id){const t=S.tx.find(x=>x.id===id);if(!t||t.type!=='Expense')return;splitTxId.value=id;splitTotalLabel.textContent=`Total: ${money(txRsd(t),'RSD')}`;splitRows.innerHTML='';for(const r of (t.splits?.length?t.splits:[{category:t.category||'Other',rsdAmount:txRsd(t)}]))addSplitRow(r.category,r.rsdAmount);splitDlg.showModal()};
  window.addSplitRow=function(category='Other',amount=''){const row=document.createElement('div');row.className='split-row';row.innerHTML=`<label>Category<select class="splitCat">${cats.map(c=>`<option ${c===category?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>RSD<input class="splitAmt" type="number" min="0" step="0.01" value="${esc(amount)}"></label><button type="button">×</button>`;row.querySelector('button').onclick=()=>row.remove();splitRows.appendChild(row)};
  window.saveSplit=function(e){e.preventDefault();const t=S.tx.find(x=>x.id===splitTxId.value);if(!t)return;const parts=[...splitRows.querySelectorAll('.split-row')].map(r=>({category:r.querySelector('.splitCat').value,rsdAmount:+r.querySelector('.splitAmt').value||0})).filter(x=>x.rsdAmount>0),sum=parts.reduce((x,p)=>x+p.rsdAmount,0),total=txRsd(t);if(!parts.length)return alert('Add at least one split.');if(Math.abs(sum-total)>0.01)return alert(`Split amounts must equal ${money(total,'RSD')}. Current total: ${money(sum,'RSD')}`);t.splits=parts;t.category='Split';splitDlg.close();save()};

  function parseCsv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){cell+='"';i++}else q=!q}else if(c===','&&!q){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(x=>x.trim()))rows.push(row);row=[]}else cell+=c}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}
  function findCol(h,names){for(const n of names){const i=h.findIndex(x=>x.includes(n));if(i>=0)return i}return -1}function fingerprint(t){return normalize(`${t.date}|${t.account}|${Number(t.amount).toFixed(2)}|${t.desc}`)}function addImported(t){const fp=fingerprint(t);if(S.importFingerprints.includes(fp)||S.tx.some(x=>fingerprint(x)===fp))return false;S.importFingerprints.push(fp);if(S.importFingerprints.length>1500)S.importFingerprints=S.importFingerprints.slice(-1500);S.tx.push({...t,id:crypto.randomUUID(),imported:true});return true}
  window.importBankCsv=async function(input){const f=input.files?.[0];if(!f)return;try{const rows=parseCsv(await f.text());if(rows.length<2)throw new Error();const h=rows[0].map(x=>normalize(x)),dateI=findCol(h,['date','datum','ngay']),descI=findCol(h,['description','merchant','details','opis','narrative','content']),amtI=findCol(h,['amount','iznos','so tien']),debitI=findCol(h,['debit','duguje']),creditI=findCol(h,['credit','potrazuje']),curI=findCol(h,['currency','valuta']),accI=findCol(h,['account','racun','card']);let added=0;for(const r of rows.slice(1)){let rawAmt=amtI>=0?numberSmart(r[amtI]):0,debit=debitI>=0?Math.abs(numberSmart(r[debitI])):0,credit=creditI>=0?Math.abs(numberSmart(r[creditI])):0,type=credit>0?'Income':'Expense',amt=credit||debit||Math.abs(rawAmt);if(!amt)continue;if(rawAmt<0)type='Expense';let account=findAccountFromText(accI>=0?r[accI]:'')||S.accounts.find(a=>!a.planned)?.id;if(!account)continue;const a=acc(account),currency=(curI>=0&&['RSD','VND','EUR'].includes(String(r[curI]).trim().toUpperCase()))?String(r[curI]).trim().toUpperCase():a.currency,date=parseAnyDate(dateI>=0?r[dateI]:'')||new Date().toISOString().slice(0,10),desc=(descI>=0?r[descI]:'Bank transaction')||'Bank transaction',amount=conv(amt,currency,a.currency),rsd=conv(amt,currency,'RSD'),vnd=conv(amt,currency,'VND');if(addImported({type,date,account,to:'',amount,rsdAmount:rsd,vndAmount:vnd,category:type==='Expense'?receiptCategory(desc):'Other',desc:String(desc).trim(),rsdConfirmed:currency==='RSD'}))added++}persist();render();renderV7();bankImportStatus.textContent=`Imported ${added} new transaction${added===1?'':'s'}; duplicates were skipped.`}catch(e){bankImportStatus.textContent='Could not understand this CSV. Try a statement export with date, description and amount columns.'}finally{input.value=''}};
  function parseAnyDate(v){const s=String(v||'').trim();if(/^\d{4}-\d{2}-\d{2}/.test(s))return s.slice(0,10);let m=s.match(/(\d{1,2})[.\/-](\d{1,2})[.\/-](\d{2,4})/);if(m){let y=m[3].length===2?'20'+m[3]:m[3];return `${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`}return ''}
  function findAccountFromText(s){const x=normalize(s),aliases=[['tpbank','tpbank'],['techcombank','techcombank'],['tcb','techcombank'],['bidv','bidv'],['mbbank','mbbank-jys'],['vietin company','vietin-company'],['vietin ceo','vietin-ceo']];for(const [k,id] of aliases)if(x.includes(k))return id;return S.accounts.find(a=>x&&normalize(a.name).includes(x))?.id||''}
  window.importBankAlert=function(){const text=bankAlertText.value.trim(),a=acc(bankAlertAccount.value);if(!text||!a)return alert('Paste an alert and choose an account.');const p=parseAlert(text,a);if(!p)return alert('I could not find a transaction amount in that alert.');if(addImported(p)){persist();render();renderV7();bankAlertText.value='';bankImportStatus.textContent='Imported 1 bank alert.'}else bankImportStatus.textContent='That transaction appears to be a duplicate.'};
  function parseAlert(text,a){const date=(text.match(/\b\d{1,2}[.\/-]\d{1,2}[.\/-]\d{2,4}\b/)||[])[0],vnd=matchCurrencyAmount(text,'VND'),rsd=matchCurrencyAmount(text,'RSD'),eur=matchCurrencyAmount(text,'EUR'),currency=vnd?'VND':rsd?'RSD':eur?'EUR':a.currency,amt=vnd||rsd||eur||matchLooseAmount(text);if(!amt)return null;const type=/credited|received|nhan|nhận|incoming|uplata|priliv/i.test(text)&&!/debited|spent|purchase|payment|chi|trừ|minus|odliv/i.test(text)?'Income':'Expense',d=parseAnyDate(date)||new Date().toISOString().slice(0,10),merchant=detectMerchantFromAlert(text);return {type,date:d,account:a.id,to:'',amount:conv(amt,currency,a.currency),rsdAmount:conv(amt,currency,'RSD'),vndAmount:conv(amt,currency,'VND'),category:type==='Expense'?receiptCategory(merchant||text):'Other',desc:merchant||'Bank alert',rsdConfirmed:currency==='RSD'}}
  function matchCurrencyAmount(text,c){const m=text.match(new RegExp('([0-9][0-9., ]{0,18})\\s*'+c,'i'))||text.match(new RegExp(c+'\\s*([0-9][0-9., ]{0,18})','i'));return m?numberSmart(m[1]):0}function matchLooseAmount(text){const m=text.match(/(?:amount|iznos|số tiền|so tien|transakcija|transaction)\D{0,12}([0-9][0-9., ]{0,18})/i);return m?numberSmart(m[1]):0}
  function numberSmart(s){s=String(s).replace(/\s/g,'').replace(/[^0-9,.-]/g,'');if(s.includes(',')&&s.includes('.')){if(s.lastIndexOf(',')>s.lastIndexOf('.'))s=s.replace(/\./g,'').replace(',','.');else s=s.replace(/,/g,'')}else if(s.includes(',')){const d=s.split(',').pop().length;s=d===2?s.replace(',','.'):s.replace(/,/g,'')}else if((s.match(/\./g)||[]).length>1)s=s.replace(/\./g,'');return Number(s)||0}function detectMerchantFromAlert(text){const m=text.match(/(?:at|merchant|kod|mesto|place|tại|tai)[:\s-]+([^,;\n]{3,60})/i);return m?m[1].trim():String(text).split(/\n/)[0].slice(0,60)}
  function processShortcutImport(){const q=new URLSearchParams(location.search);if(!q.has('bank')&&!q.has('amount'))return;const id=findAccountFromText(q.get('bank')||'')||q.get('account')||'',a=acc(id);if(!a)return;const type=(q.get('type')||'expense').toLowerCase()==='income'?'Income':'Expense',currency=(q.get('currency')||a.currency).toUpperCase(),amt=numberSmart(q.get('amount')||''),rsd=numberSmart(q.get('rsd')||''),desc=q.get('merchant')||q.get('description')||'Shortcut bank import';if(!amt&&!rsd)return;const amount=amt?conv(amt,currency,a.currency):conv(rsd,'RSD',a.currency),obj={type,date:q.get('date')||new Date().toISOString().slice(0,10),account:id,to:'',amount,rsdAmount:rsd||conv(amount,a.currency,'RSD'),vndAmount:conv(amount,a.currency,'VND'),category:q.get('category')||(type==='Expense'?receiptCategory(desc):'Other'),desc,rsdConfirmed:!!rsd};if(addImported(obj)){persist();setTimeout(()=>{render();renderV7()},100)}history.replaceState(null,'',location.pathname+location.hash)}

  window.renderMonthlyReport=function(){const el=document.getElementById('monthlyReport');if(!el)return;const m=document.getElementById('reportMonth')?.value||month(),ex=monthExpenses(m),inc=monthIncome(m),e=sumExpenseRsd(ex),i=sumIncomeRsd(inc),saveAmt=i-e,rate=i?saveAmt/i*100:0,cm=categoryMap(ex),top=Object.entries(cm).sort((a,b)=>b[1]-a[1])[0],over=S.budgets.map(b=>({b,spent:budgetSpent(b,m)})).filter(x=>x.spent>x.b.amount),amounts=ex.map(txRsd).sort((a,b)=>a-b),median=amounts.length?amounts[Math.floor(amounts.length/2)]:0,unusual=ex.filter(t=>median>0&&txRsd(t)>=median*2.5).sort((a,b)=>txRsd(b)-txRsd(a)).slice(0,5);el.innerHTML=`<div class="v7-grid"><div class="v7-stat"><small>Income</small><strong>${money(i,'RSD')}</strong></div><div class="v7-stat"><small>Expenses</small><strong>${money(e,'RSD')}</strong></div><div class="v7-stat"><small>Net savings</small><strong class="${saveAmt>=0?'v7-positive':'v7-negative'}">${money(saveAmt,'RSD')}</strong></div><div class="v7-stat"><small>Savings rate</small><strong>${rate.toFixed(1)}%</strong></div></div><h3 style="margin-top:14px">Summary</h3><div>${top?`Top category: <strong>${esc(top[0])}</strong> (${money(top[1],'RSD')}).`:'No categorized expenses.'} ${over.length?`<strong>${over.length}</strong> budget${over.length>1?'s':''} exceeded.`:'No budgets exceeded.'}</div><h3 style="margin-top:14px">Largest / unusual expenses</h3>${unusual.length?unusual.map(t=>`<div class="v7-line"><span>${esc(t.desc||t.category||'Expense')}</span><strong>${money(txRsd(t),'RSD')}</strong></div>`).join(''):'<div class="muted">No unusual expenses detected.</div>'}`};
  window.exportMonthlyCsv=function(){const m=document.getElementById('reportMonth')?.value||month(),rows=[['date','type','account','description','category','RSD','VND']];for(const t of S.tx.filter(t=>t.date?.startsWith(m)))rows.push([t.date,t.type,acc(t.account)?.name||'',t.desc||'',t.category||'',txRsd(t),txVnd(t)]);const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`triledger-${m}.csv`;a.click()};
  function renderMerchantRules(){const el=document.getElementById('merchantRulesList');if(!el)return;const entries=Object.entries(S.merchantRules||{}).sort();el.innerHTML=entries.length?entries.map(([m,c])=>`<div class="row"><div><strong>${esc(m)}</strong><small>Automatically categorize as ${esc(c)}</small></div><button onclick="deleteMerchantRule('${encodeURIComponent(m)}')">Forget</button></div>`).join(''):'<div class="empty">Merchant memory learns automatically when you save categorized transactions.</div>'}window.deleteMerchantRule=function(encoded){delete S.merchantRules[decodeURIComponent(encoded)];save()};
})();
