(()=>{
  function wait(){let n=0;const timer=setInterval(()=>{n++;try{if(window.__triledgerV9&&typeof S!=='undefined'&&typeof persist==='function'){clearInterval(timer);setup()}else if(n>260)clearInterval(timer)}catch(e){if(n>260)clearInterval(timer)}},50)}
  function setup(){if(window.__triledgerV10)return;window.__triledgerV10=true;const result=mergeLegacy();persist();render();if(window.renderBudgetV8)renderBudgetV8();showStatus(result)}
  function parseKey(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}
  function norm(s){return String(s||'').trim().toLowerCase()}
  function txFp(t){return [t.date||'',t.type||'',t.account||'',Number(t.amount||0).toFixed(2),Number(t.rsdAmount||0).toFixed(2),Number(t.vndAmount||0).toFixed(2),norm(t.desc||t.description||'')].join('|')}
  function accFp(a){return norm(a.name)+'|'+(a.currency||'')+'|'+(a.scope||'')}
  function budFp(b){return norm(b.category)+'|'+norm(b.scope)+'|'+(b.currency||'')+'|'+Number(b.amount||0)}
  function mergeLegacy(){let addedA=0,addedT=0,addedB=0,addedC=0;const sources=[];const old=parseKey('triledger-v1');if(old)sources.push(convertOld(old));for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k||k==='triledger-finance-v1'||k==='triledger-v1'||k==='triledger-custom-categories-v1')continue;if(/^triledger/i.test(k)){const x=parseKey(k);if(x&&typeof x==='object')sources.push(convertOld(x))}}
    const af=new Set((S.accounts||[]).map(accFp)),tf=new Set((S.tx||[]).map(txFp)),bf=new Set((S.budgets||[]).map(budFp));for(const src of sources){for(const a0 of src.accounts||[]){const a=normalizeAccount(a0),f=accFp(a);if(!af.has(f)){S.accounts.push(a);af.add(f);addedA++}}for(const t0 of src.tx||src.transactions||[]){const t=normalizeTx(t0),f=txFp(t);if(!tf.has(f)){S.tx.push(t);tf.add(f);addedT++}}for(const b0 of src.budgets||[]){const b=normalizeBudget(b0),f=budFp(b);if(!bf.has(f)){S.budgets.push(b);bf.add(f);addedB++}}}
    try{const cc=JSON.parse(localStorage.getItem('triledger-custom-categories-v1')||'[]');if(Array.isArray(cc))for(const c of cc){if(typeof c==='string'&&!cats.some(x=>norm(x)===norm(c))){cats.push(c);addedC++}}}catch{}return {addedA,addedT,addedB,addedC}}
  function convertOld(x){if(!x||typeof x!=='object')return {};return {accounts:Array.isArray(x.accounts)?x.accounts:[],tx:Array.isArray(x.tx)?x.tx:Array.isArray(x.transactions)?x.transactions:[],budgets:Array.isArray(x.budgets)?x.budgets:[]}}
  function normalizeAccount(a){return {id:a.id||crypto.randomUUID(),name:a.name||a.bank||'Recovered account',group:a.group||(a.type==='Cash'?'Cash':a.scope==='Business'?'JYS business accounts':'Personal bank accounts'),scope:a.scope==='Business'?'JYS Business':(a.scope||'Personal'),type:a.type||'Bank',currency:a.currency||'VND',opening:Number(a.opening??a.openingBalance??a.balance??0)||0,planned:!!a.planned}}
  function normalizeTx(t){const account=t.account||t.accountId||t.from||'';const amount=Number(t.amount??t.value??0)||0;return {id:t.id||crypto.randomUUID(),type:t.type||'Expense',date:t.date||t.createdAt?.slice?.(0,10)||new Date().toISOString().slice(0,10),account,to:t.to||t.toAccount||'',amount,rsdAmount:Number(t.rsdAmount??(t.currency==='RSD'?amount:0))||0,vndAmount:Number(t.vndAmount??(t.currency==='VND'?amount:0))||0,category:t.category||'Other',desc:t.desc||t.description||t.merchant||'',receiptScanned:!!t.receiptScanned,receiptText:t.receiptText||'',splits:Array.isArray(t.splits)?t.splits:undefined,imported:!!t.imported,rsdConfirmed:!!t.rsdConfirmed}}
  function normalizeBudget(b){return {id:b.id||crypto.randomUUID(),scope:b.scope==='Business'?'JYS Business':(b.scope||'Personal'),category:b.category||'Other',amount:Number(b.amount||0),currency:b.currency||'RSD'}}
  function showStatus(r){const sec=document.getElementById('settings')||document.querySelector('main');if(!sec)return;let n=document.getElementById('legacyMergeNotice');if(!n){n=document.createElement('div');n.id='legacyMergeNotice';n.className='notice';sec.insertAdjacentElement('afterbegin',n)}const total=r.addedA+r.addedT+r.addedB+r.addedC;n.innerHTML=total?`<strong>Previous TriLedger data merged</strong>Recovered ${r.addedA} accounts, ${r.addedT} transactions, ${r.addedB} budgets and ${r.addedC} categories from older local versions. Nothing existing was overwritten.`:`<strong>Previous data check complete</strong>No extra legacy records were found; the current app already contains the available older data.`}
  wait();
})();