(()=>{
let bm=(()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`})();
const st=document.createElement('style');st.textContent='.budget-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin:12px 0}.mini{border:1px solid var(--l);background:#0b1525;border-radius:14px;padding:12px}.mini strong{display:block;font-size:18px;margin-top:4px}.budget-viz{display:grid;grid-template-columns:minmax(180px,230px) 1fr;gap:16px;align-items:center}.donut{width:100%;max-width:220px;aspect-ratio:1}.legend{display:grid;gap:7px}.legend-row{display:grid;grid-template-columns:12px 1fr auto;gap:8px;align-items:center}.dot{width:10px;height:10px;border-radius:50%}.bcard{border:1px solid var(--l);border-radius:16px;padding:14px;margin:10px 0;background:#0b1525}.bhead{display:flex;justify-content:space-between;gap:10px}.btrack{height:10px;background:#17243a;border-radius:999px;overflow:hidden;margin:9px 0}.btrack i{display:block;height:100%;background:var(--a)}.audit{display:none;border-top:1px solid var(--l);margin-top:10px;padding-top:8px}.audit.open{display:block}.audit-row{display:grid;grid-template-columns:1fr auto;gap:10px;padding:8px 0;border-bottom:1px solid var(--l)}@media(max-width:650px){.budget-viz{grid-template-columns:1fr}.budget-summary{grid-template-columns:1fr 1fr}.budget-summary .mini:last-child{grid-column:1/-1}}';document.head.appendChild(st);
const sec=document.getElementById('budgets');if(sec&&!document.getElementById('budgetStableTop')){const d=document.createElement('div');d.id='budgetStableTop';d.innerHTML='<div class="toolbar"><label>Budget month <input id="stableBudgetMonth" type="month"></label></div><div class="budget-summary"><div class="mini"><small>Total planned</small><strong id="stablePlanned"></strong></div><div class="mini"><small>Spent</small><strong id="stableSpent"></strong></div><div class="mini"><small>Remaining</small><strong id="stableRemaining"></strong></div></div><div class="panel budget-viz"><svg id="stableDonut" class="donut" viewBox="0 0 220 220"></svg><div id="stableLegend" class="legend"></div></div>';sec.querySelector('.toolbar').insertAdjacentElement('afterend',d);stableBudgetMonth.value=bm;stableBudgetMonth.onchange=()=>{bm=stableBudgetMonth.value;renderStableBudgets()}}
function np(s){return String(s||'').trim().toLowerCase()}
function parts(t){return Array.isArray(t.splits)&&t.splits.length?t.splits.map(s=>({category:s.category||'Other',rsd:+s.rsdAmount||0})):[{category:t.category||'Other',rsd:txRsd(t)}]}
function match(b){const out=[];for(const t of S.tx){if(t.type!=='Expense'||!String(t.date||'').startsWith(bm)||np(acc(t.account)?.scope)!==np(b.scope))continue;for(const p of parts(t))if(np(p.category)===np(b.category)&&p.rsd>0)out.push({t,p})}return out}
function sr(b){return match(b).reduce((x,z)=>x+z.p.rsd,0)}function br(b){return b.currency==='RSD'?+b.amount||0:conv(b.amount,b.currency,'RSD')}
function audit(b){const rows=match(b);return rows.length?rows.map(({t,p})=>`<div class="audit-row"><div><strong>${t.desc||'Expense'}</strong><small>${t.date} · ${money(p.rsd,'RSD')}</small></div><select onchange="stableRecat('${t.id}',this.value)">${cats.map(c=>`<option ${np(c)===np(p.category)?'selected':''}>${c}</option>`).join('')}</select></div>`).join(''):'<div class="empty">No transactions assigned to this category.</div>'}
window.stableToggleAudit=id=>document.getElementById('sa-'+id)?.classList.toggle('open');window.stableRecat=(id,c)=>{const t=S.tx.find(x=>x.id===id);if(t){t.category=c;if(S.merchantRules&&t.desc)S.merchantRules[np(t.desc)]=c;save()}};
budgetRows=function(){return S.budgets.length?S.budgets.map(b=>{const rs=sr(b),spent=b.currency==='RSD'?rs:conv(rs,'RSD',b.currency),pct=b.amount?spent/b.amount*100:0,rem=b.amount-spent,c=match(b).length;return `<div class="bcard"><div class="bhead"><div><strong>${b.category}</strong><small>${b.scope} · ${c} transaction${c===1?'':'s'} counted</small></div><span class="badge">${pct>=100?'OVER':pct>=80?'WATCH':'OK'}</span></div><div style="display:flex;justify-content:space-between;margin-top:8px"><span>${money(spent,b.currency)} spent</span><strong>${money(b.amount,b.currency)}</strong></div><div class="btrack"><i style="width:${Math.max(0,Math.min(100,pct))}%"></i></div><small>${rem>=0?money(rem,b.currency)+' remaining':money(Math.abs(rem),b.currency)+' over'}</small><div class="actions"><button onclick="stableToggleAudit('${b.id}')">What counts?</button><button onclick="delBudget('${b.id}')">Delete</button></div><div id="sa-${b.id}" class="audit">${audit(b)}</div></div>`}).join(''):'<div class="empty">No budgets yet</div>'};
function arc(a0,a1,col){const cx=110,cy=110,r=76,ri=48,p=(a,rr)=>[cx+Math.cos(a)*rr,cy+Math.sin(a)*rr],p1=p(a0,r),p2=p(a1,r),q2=p(a1,ri),q1=p(a0,ri),large=a1-a0>Math.PI?1:0;return `<path d="M ${p1[0]} ${p1[1]} A ${r} ${r} 0 ${large} 1 ${p2[0]} ${p2[1]} L ${q2[0]} ${q2[1]} A ${ri} ${ri} 0 ${large} 0 ${q1[0]} ${q1[1]} Z" fill="${col}"/>`}
function renderDonut(){if(!window.stableDonut)return;const rows=S.budgets.map(b=>({n:b.category,v:sr(b)})).filter(x=>x.v>0).sort((a,b)=>b.v-a.v),tot=rows.reduce((x,r)=>x+r.v,0);if(!tot){stableDonut.innerHTML='<circle cx="110" cy="110" r="72" fill="none" stroke="#1b2b43" stroke-width="28"/><text x="110" y="114" text-anchor="middle" fill="#8ea1be" font-size="14">No spending</text>';stableLegend.innerHTML='<div class="muted">No budgeted expenses for this month.</div>';return}const cs=['#5f95ff','#56c79b','#d2a351','#c875e8','#ed7c86','#74b7d8','#9ea86d','#dd8b55'];let a=-Math.PI/2,h='';rows.forEach((r,i)=>{const b=a+r.v/tot*Math.PI*2;h+=arc(a,b,cs[i%cs.length]);a=b});stableDonut.innerHTML=h+`<text x="110" y="106" text-anchor="middle" fill="#eef4ff" font-size="13">Spent</text><text x="110" y="128" text-anchor="middle" fill="#eef4ff" font-size="17" font-weight="700">${Math.round(tot).toLocaleString()} RSD</text>`;stableLegend.innerHTML=rows.map((r,i)=>`<div class="legend-row"><span class="dot" style="background:${cs[i%cs.length]}"></span><span>${r.n}</span><strong>${Math.round(r.v).toLocaleString()}</strong></div>`).join('')}
window.renderStableBudgets=function(){if(!document.getElementById('budgetList'))return;budgetList.innerHTML=budgetRows();const p=S.budgets.reduce((x,b)=>x+br(b),0),s=S.budgets.reduce((x,b)=>x+sr(b),0);stablePlanned.textContent=money(p,'RSD');stableSpent.textContent=money(s,'RSD');stableRemaining.textContent=money(p-s,'RSD');renderDonut()};
const r0=render;render=function(){r0();renderStableBudgets()};renderStableBudgets();
})();
