(()=>{
let custom=[];try{custom=JSON.parse(localStorage.getItem('triledger-custom-categories-v1')||'[]');if(!Array.isArray(custom))custom=[]}catch{}for(const c of custom)if(typeof c==='string'&&!cats.some(x=>x.toLowerCase()===c.toLowerCase()))cats.push(c);
const oldFill=fillSelects;fillSelects=function(){oldFill();const h=cats.map(c=>`<option>${c}</option>`).join('');tcat.innerHTML=h;bcat.innerHTML=h};
window.openIncome=()=>{openTx(false);ttype.value='Income';txFormMode();setTimeout(()=>tamount.focus(),40)};
if(!document.getElementById('categoryDlg')){const d=document.createElement('dialog');d.id='categoryDlg';d.innerHTML='<form id="catForm" class="forms"><label class="full">New category<input id="newCat" required maxlength="40"></label><div class="actions full"><button type="button" id="catCancel">Cancel</button><button class="primary">Add</button></div></form>';document.body.appendChild(d);d.querySelector('#catCancel').onclick=()=>d.close();d.querySelector('#catForm').onsubmit=e=>{e.preventDefault();const c=d.querySelector('#newCat').value.trim();if(!c)return;if(cats.some(x=>x.toLowerCase()===c.toLowerCase()))return alert('Category already exists.');cats.push(c);custom.push(c);localStorage.setItem('triledger-custom-categories-v1',JSON.stringify(custom));d.close();render()};window.openCategory=()=>{d.querySelector('#newCat').value='';d.showModal()}}
function qButton(text,fn,id){const b=document.createElement('button');b.textContent=text;b.id=id;b.onclick=fn;return b}
const head=document.querySelector('header .toolbar-actions');if(head&&!document.getElementById('qIncome')){head.insertBefore(qButton('+ Income',openIncome,'qIncome'),head.lastElementChild);head.insertBefore(qButton('+ Category',openCategory,'qCategory'),head.lastElementChild)}
const txa=document.querySelector('#tx .toolbar-actions');if(txa&&!document.getElementById('txIncome')){txa.append(qButton('+ Income',openIncome,'txIncome'),qButton('+ Category',openCategory,'txCategory'))}
const oldCat=categoryRows;categoryRows=function(expenses){if(expenses.length)return oldCat(expenses);const months=[...new Set(S.tx.filter(t=>t.type==='Expense').map(t=>String(t.date||'').slice(0,7)).filter(Boolean))].sort().reverse();if(!months.length)return '<div class="empty">No expenses yet</div>';const m=months[0],ex=S.tx.filter(t=>t.type==='Expense'&&String(t.date||'').startsWith(m));return `<div class="help">No expenses this month. Showing ${m}.</div>`+oldCat(ex)};
const oldRender=render;render=function(){oldRender();const s=document.getElementById('settings');if(s&&!document.getElementById('dataStatus')){const m=window.__legacyMerge||{},n=document.createElement('div');n.id='dataStatus';n.className='notice';n.innerHTML=`<strong>Original v5 data is active</strong>This build reads the same <code>triledger-finance-v1</code> database. Current profile: ${S.tx.length} transactions, ${S.budgets.length} budgets, ${S.accounts.length} accounts.${m.transactions?` Recovered ${m.transactions} older transaction(s).`:''}`;s.insertAdjacentElement('afterbegin',n)}};
render();
})();
